#!/usr/bin/env bun

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { parseArgs } from "node:util";
import { frontmatter } from "./check-config";
import { codexConfigPlan, describePolicy } from "./lib/host-config";
import { backupDestination, hookFilePlan, installHookFile, nativeHookConfig } from "./lib/native-hooks";

export function coreSkillNames(projectRoot: string): string[] {
  return fs.readdirSync(path.join(projectRoot, ".claude", "skills"), { withFileTypes: true })
    .filter(entry => entry.isDirectory() && fs.existsSync(path.join(projectRoot, ".claude", "skills", entry.name, "SKILL.md")))
    .map(entry => entry.name).sort();
}

export const PORTABLE_SKILLS = coreSkillNames(path.resolve(import.meta.dir, "../.."));

export interface CodexLink {
  source: string;
  dest: string;
  type: "file" | "directory";
  /** Generated file: dest = source + these sources concatenated. Codex has no
   * append-style include (model_instructions_file REPLACES the built-ins), so the
   * system prompt rides inside AGENTS.md. Installs as a real file on every OS —
   * re-run the sync after editing any source. */
  concatSources?: string[];
  /** Generated native entrypoint; shared command bodies are read from source. */
  content?: string;
  append?: string;
}

export type LinkStatus = "missing" | "linked" | "local" | "conflict" | "stale";

export function buildCodexLinks(
  projectRoot: string,
  homeDir: string,
  codexHome = path.join(homeDir, ".codex"),
): CodexLink[] {
  const codexRoot = codexHome;
  return [
    {
      source: path.join(projectRoot, "CLAUDE.md"),
      dest: path.join(codexRoot, "AGENTS.md"),
      type: "file",
      concatSources: [
        path.join(projectRoot, ".claude", "system-prompts", "poneglyph-sp.md"),
        path.join(projectRoot, ".claude", "rules", "harness-runtime.md"),
      ],
      append: `Poneglyph source root: ${projectRoot.replaceAll("\\", "/")}\n`,
    },
    ...coreSkillNames(projectRoot).map((name) => ({
      source: path.join(projectRoot, ".claude", "skills", name),
      dest: path.join(codexRoot, "skills", name),
      type: "directory" as const,
    })),
    ...fs.readdirSync(path.join(projectRoot, ".claude", "commands")).filter(name => name.endsWith(".md")).sort().map(file => {
      const source = path.join(projectRoot, ".claude", "commands", file);
      const name = file.slice(0, -3);
      const { fields } = frontmatter(fs.readFileSync(source, "utf8"));
      if (typeof fields.description !== "string") throw new Error(`Missing command description: ${file}`);
      return {
        source, dest: path.join(codexRoot, "skills", name, "SKILL.md"), type: "file" as const,
        content: `---\nname: ${name}\ndescription: ${JSON.stringify(fields.description.trim())}\n---\n\n` +
          `<!-- generated by sync-codex; edit the shared command source -->\n\n` +
          `Read ${source.replaceAll("\\", "/")} in full and follow that command.\n` +
          `Use the user's text after $${name} as the command arguments ($ARGUMENTS).\n` +
          `Apply the installed Poneglyph host contract. Keep its existing approval gates.\n` +
          `Resolve Poneglyph helpers from ${projectRoot.replaceAll("\\", "/")}; keep project artifacts in the current project.\n`,
      };
    }),
  ];
}

function exists(p: string): boolean {
  try {
    fs.lstatSync(p);
    return true;
  } catch {
    return false;
  }
}

function targetMatches(link: CodexLink): boolean {
  try {
    if (!fs.lstatSync(link.dest).isSymbolicLink()) return false;
    // Windows junctions readlink with the \\?\ long-path prefix — strip it.
    const target = fs.readlinkSync(link.dest).replace(/^\\\\\?\\/, "");
    const resolved = path.resolve(path.dirname(link.dest), target);
    return path.resolve(resolved) === path.resolve(link.source);
  } catch {
    return false;
  }
}

// Windows: directory junctions need no privileges; file symlinks require
// developer mode, so the doctrine file is installed as a copy instead.
export function linkMethodFor(
  type: CodexLink["type"],
  platform: NodeJS.Platform = process.platform,
): "symlink" | "junction" | "copy" {
  if (platform !== "win32") return "symlink";
  return type === "directory" ? "junction" : "copy";
}

const GENERATED_MARK = "<!-- generated by sync-codex";

// Codex silently stops reading project guidance at `project_doc_max_bytes`
// (32 KiB default) — a generated AGENTS.md over budget would lose its TAIL
// (the SP's aliases and examples) with zero symptoms. Warn near the cliff.
export const CODEX_DOC_BUDGET = 32 * 1024;

export function codexBudgetVerdict(bytes: number): "ok" | "warn" | "over" {
  if (bytes > CODEX_DOC_BUDGET) return "over";
  if (bytes >= CODEX_DOC_BUDGET * 0.9) return "warn";
  return "ok";
}

export function generatedContent(link: CodexLink): string | null {
  if (link.content !== undefined) return link.content;
  if (!link.concatSources?.length) return null;
  const sources = [link.source, ...link.concatSources];
  const parts = sources.map((p) => fs.readFileSync(p, "utf8").trimEnd());
  // One short line: Codex reads this file every session — provenance must not add noise.
  return `${GENERATED_MARK} — edit CLAUDE.md / poneglyph-sp.md, then re-sync -->\n\n${parts.join("\n\n---\n\n")}\n${link.append ?? ""}`;
}

function copyMatches(link: CodexLink): boolean {
  try {
    // An account profile can link to the shared generated doctrine. Preserve
    // that link when its target already contains the complete expected output.
    if (!fs.statSync(link.dest).isFile()) return false;
    const expected = generatedContent(link) ?? fs.readFileSync(link.source, "utf8");
    return fs.readFileSync(link.dest, "utf8") === expected;
  } catch {
    return false;
  }
}

export function linkStatus(link: CodexLink, platform: NodeJS.Platform = process.platform): LinkStatus {
  if (!exists(link.dest)) return "missing";
  if (link.concatSources?.length || link.content !== undefined) {
    // Generated files are content-compared on every OS. An out-of-date file we
    // generated ourselves is "stale" (safe to regenerate without backup); a
    // divergent symlink or a hand-made file needs --backup.
    if (copyMatches(link)) return "linked";
    try {
      if (fs.lstatSync(link.dest).isSymbolicLink()) return "conflict";
      return fs.readFileSync(link.dest, "utf8").includes(GENERATED_MARK) ? "stale" : "local";
    } catch {
      return "missing";
    }
  }
  if (targetMatches(link)) return "linked";
  // Where the install method is a copy, a content-equal copy is healthy.
  if (linkMethodFor(link.type, platform) === "copy" && copyMatches(link)) return "linked";
  try {
    return fs.lstatSync(link.dest).isSymbolicLink() ? "conflict" : "local";
  } catch {
    return "missing";
  }
}

export function createLink(link: CodexLink, backup: boolean): void {
  const generated = generatedContent(link);
  if (link.concatSources?.length && generated !== null && codexBudgetVerdict(Buffer.byteLength(generated)) === "over") {
    throw new Error(`${link.dest} exceeds the ${CODEX_DOC_BUDGET}-byte instruction budget.`);
  }
  const status = linkStatus(link);
  if (status === "linked") return;
  if (status !== "missing" && status !== "stale") {
    if (!backup) {
      throw new Error(`${link.dest} already exists; rerun with --backup to replace it`);
    }
    const backupPath = backupDestination(link.dest);
    fs.renameSync(link.dest, backupPath);
    console.log(`backup: ${link.dest} -> ${backupPath}`);
  }
  fs.mkdirSync(path.dirname(link.dest), { recursive: true });
  if (generated !== null) {
    const bytes = Buffer.byteLength(generated, "utf8");
    const verdict = codexBudgetVerdict(bytes);
    if (link.concatSources?.length && verdict === "over") {
      throw new Error(
        `${link.dest} would be ${bytes} bytes — over Codex's ${CODEX_DOC_BUDGET}-byte project_doc_max_bytes budget; Codex would silently truncate the tail. Trim CLAUDE.md or the SP first.`,
      );
    }
    fs.writeFileSync(link.dest, generated);
    if (link.concatSources?.length && verdict === "warn") {
      console.log(`🟡 ${link.dest}: ${bytes} bytes — over 90% of Codex's ${CODEX_DOC_BUDGET}-byte budget`);
    }
    console.log(`generated ${link.dest}; re-run the sync after editing its sources`);
    return;
  }
  const method = linkMethodFor(link.type);
  if (method === "copy") {
    fs.copyFileSync(link.source, link.dest);
    console.log(
      `copied ${link.dest} (Windows file symlinks need developer mode); re-run the sync after editing ${path.basename(link.source)}`,
    );
  } else {
    fs.symlinkSync(
      link.source,
      link.dest,
      method === "junction" ? "junction" : link.type === "directory" ? "dir" : "file",
    );
  }
}

function printStatus(links: CodexLink[]): void {
  for (const link of links) {
    console.log(`${linkStatus(link).padEnd(8)} ${link.dest}`);
  }
}

// Generated command wrappers whose shared command no longer exists (removed or renamed):
// `$name` would still be advertised but read a missing file. Only files carrying
// GENERATED_MARK qualify — linked skill directories and foreign skills never match.
export function staleWrappers(codexHome: string, links: CodexLink[]): string[] {
  const skillsDir = path.join(codexHome, "skills");
  if (!fs.existsSync(skillsDir)) return [];
  const managed = new Set(links.filter((l) => l.content !== undefined).map((l) => path.resolve(l.dest)));
  return fs.readdirSync(skillsDir)
    .map((name) => path.join(skillsDir, name, "SKILL.md"))
    .filter((file) => {
      if (managed.has(path.resolve(file))) return false;
      try {
        return fs.statSync(file).isFile() && fs.readFileSync(file, "utf8").includes(GENERATED_MARK);
      } catch {
        return false;
      }
    });
}

function removeStaleWrappers(codexHome: string, links: CodexLink[]): void {
  for (const file of staleWrappers(codexHome, links)) {
    fs.rmSync(file);
    try { fs.rmdirSync(path.dirname(file)); } catch { /* directory not empty: leave it */ }
    console.log(`removed  ${file} (generated wrapper; its command no longer exists)`);
  }
}

function usage(): void {
  console.log(`
sync-codex - install Poneglyph's portable Codex adapter

Usage:
  bun .claude/scripts/sync-codex.ts [--status|--execute|--unlink] [--backup] [--force]

Installs:
  ~/.codex/AGENTS.md       GENERATED: doctrine (CLAUDE.md) + system prompt
                           (.claude/system-prompts/poneglyph-sp.md) concatenated.
                           Codex has no append-style include, so this is a real
                           file on every OS - re-run the sync after editing
                           CLAUDE.md or poneglyph-sp.md.
  ~/.codex/skills/*       Core skill directory junctions and generated command entrypoints.
  ~/.codex/hooks.json     Three native hook adapters; existing host hooks are preserved.

Review new native hooks in Codex /hooks before they can run. The installer never
grants trust or copies Claude permissions. Grok keeps its own native adapter.

On Windows, skills install as directory junctions (no admin).
CODEX_HOME selects an account profile; its default is ~/.codex.
An existing link to matching generated doctrine is preserved. Sync its shared
target profile first when that doctrine needs regeneration.
`);
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      status: { type: "boolean", default: false },
      execute: { type: "boolean", default: false },
      unlink: { type: "boolean", default: false },
      backup: { type: "boolean", default: false },
      force: { type: "boolean", default: false },
      help: { type: "boolean", short: "h", default: false },
    },
  });
  if (values.help) return usage();

  if ((values.execute || values.unlink) && !values.force && !process.stdin.isTTY) {
    throw new Error("non-interactive mutation requires --force");
  }

  const projectRoot = fs.realpathSync.native(path.resolve(import.meta.dir, "../.."));
  const codexHome = process.env.CODEX_HOME ? path.resolve(process.env.CODEX_HOME) : undefined;
  const profile = codexHome ?? path.join(os.homedir(), ".codex");
  const links = buildCodexLinks(projectRoot, os.homedir(), codexHome);
  const hookFile = path.join(profile, "hooks.json");
  const hooks = nativeHookConfig("codex", projectRoot);
  hookFilePlan(hookFile, hooks); // Validate configuration before any mutation.
  // Context/effort policy keys in the profile's config.toml (plan 037); other keys are preserved.
  const configFile = path.join(profile, "config.toml");
  const configPlan = () => codexConfigPlan(fs.existsSync(configFile) ? fs.readFileSync(configFile, "utf8") : "");
  const status = () => {
    printStatus(links);
    for (const file of staleWrappers(profile, links)) console.log(`stale    ${file} (generated wrapper; its command no longer exists)`);
    console.log(`${hookFilePlan(hookFile, hooks).status.padEnd(8)} ${hookFile}`);
    console.log(`${(configPlan().changed ? "stale" : "linked").padEnd(8)} ${configFile} (${describePolicy("codex")})`);
    console.log("Native hook execution requires Codex /hooks trust; registration alone is not activation evidence.");
  };
  if (values.status) return status();

  if (values.unlink) {
    if (!values.backup) throw new Error("Uninstall requires --backup to preserve links and generated entries.");
    if (fs.existsSync(hookFile)) installHookFile(hookFile, hooks, false);
    for (const link of links) {
      if (linkStatus(link) !== "linked") continue;
      const backup = backupDestination(link.dest);
      fs.renameSync(link.dest, backup);
      console.log(`backup: ${link.dest} -> ${backup}`);
    }
    console.log("Removed matching Poneglyph entries and native hooks; unrelated skills and handlers are preserved.");
    return;
  }

  if (!values.execute) {
    status();
    console.log("preview only; pass --execute to create missing links");
    return;
  }

  // Preflight the complete plan before touching an installed entry.
  for (const link of links) {
    const state = linkStatus(link);
    const generated = generatedContent(link);
    if (link.concatSources?.length && generated !== null && Buffer.byteLength(generated) > CODEX_DOC_BUDGET) throw new Error("Generated doctrine exceeds its budget.");
    if ((state === "local" || state === "conflict") && !values.backup) throw new Error(`Review collision at ${link.dest}; replacement requires --backup.`);
    if (!fs.existsSync(link.source)) throw new Error(`Source missing: ${link.source}`);
  }
  const plan = configPlan();
  if (plan.changed && fs.existsSync(configFile) && !values.backup) throw new Error("Context policy change in config.toml requires --backup.");
  for (const link of links) createLink(link, values.backup ?? false);
  removeStaleWrappers(profile, links);
  installHookFile(hookFile, hooks);
  if (plan.changed) {
    if (fs.existsSync(configFile)) {
      const backup = backupDestination(configFile);
      fs.copyFileSync(configFile, backup);
      if (!fs.readFileSync(configFile).equals(fs.readFileSync(backup))) throw new Error("Codex recovery verification failed.");
      console.log(`backup: ${configFile} -> ${backup}`);
    }
    fs.mkdirSync(path.dirname(configFile), { recursive: true });
    fs.writeFileSync(configFile, plan.content);
  }
  status();
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(`sync-codex failed: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  });
}
