import { describe, expect, it } from "bun:test";
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, readlinkSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import * as path from "node:path";
import { buildCodexLinks, codexBudgetVerdict, CODEX_DOC_BUDGET, generatedContent, linkMethodFor, linkStatus, PORTABLE_SKILLS } from "../sync-codex.ts";

describe("codex 32KiB budget guard", () => {
  it("ok below 90%, warn at 90%+, over past the budget", () => {
    expect(codexBudgetVerdict(20_000)).toBe("ok");
    expect(codexBudgetVerdict(CODEX_DOC_BUDGET * 0.9)).toBe("warn");
    expect(codexBudgetVerdict(CODEX_DOC_BUDGET)).toBe("warn");
    expect(codexBudgetVerdict(CODEX_DOC_BUDGET + 1)).toBe("over");
  });
});

describe("Codex adapter topology", () => {
  const root = path.resolve(import.meta.dir, "../../..");
  const links = buildCodexLinks(root, "/home/oriol");

  it("generates the doctrine+system-prompt AGENTS.md and links the portable skill allowlist", () => {
    // path.join on every entry: the implementation joins natively, so literal
    // "/"-separated strings only matched on POSIX (audit 010, Windows suite).
    expect(links[0].source).toBe(path.join(root, "CLAUDE.md"));
    expect(links[0].dest).toBe(path.join("/home/oriol", ".codex", "AGENTS.md"));
    const sourceSkills = readdirSync(path.join(root, ".claude", "skills"), { withFileTypes: true })
      .filter(entry => entry.isDirectory() && existsSync(path.join(root, ".claude", "skills", entry.name, "SKILL.md")));
    expect(links.filter(link => link.type === "directory").map(link => path.basename(link.source)).sort()).toEqual(sourceSkills.map(entry => entry.name).sort());
  });

  it("uses generated command entrypoints that refer to the shared source", () => {
    const commands = links.filter(link => link.content !== undefined);
    expect(commands).toHaveLength(5);
    for (const link of commands) {
      expect(link.content).toContain(link.source.replaceAll("\\", "/"));
      expect(link.content).toContain("$ARGUMENTS");
      expect(link.content).not.toContain("# /flow — feature lifecycle orchestrator");
    }
  });

  it("installs and inspects an isolated CODEX_HOME without changing its config", () => {
    const profile = mkdtempSync(path.join(tmpdir(), "codex-profile-"));
    const config = path.join(profile, "config.toml");
    writeFileSync(config, "# Account-owned configuration\n");
    const foreignHooks = { hooks: { SessionStart: [{ hooks: [{ type: "command", command: "existing-integration" }] }] } };
    writeFileSync(path.join(profile, "hooks.json"), JSON.stringify(foreignHooks));
    const script = path.resolve(import.meta.dir, "../sync-codex.ts");
    const env = { ...process.env, CODEX_HOME: profile };
    const installed = Bun.spawnSync([process.execPath, script, "--execute", "--force"], { env });
    expect(installed.exitCode).toBe(0);
    expect(readFileSync(config, "utf8")).toBe("# Account-owned configuration\n");
    expect(readFileSync(path.join(profile, "AGENTS.md"), "utf8")).toStartWith("<!-- generated by sync-codex");
    for (const name of PORTABLE_SKILLS) expect(existsSync(path.join(profile, "skills", name, "SKILL.md"))).toBe(true);
    expect(existsSync(path.join(profile, "hooks"))).toBe(false);
    expect(JSON.parse(readFileSync(path.join(profile, "hooks.json"), "utf8")).hooks.SessionStart).toEqual(foreignHooks.hooks.SessionStart);
    const status = Bun.spawnSync([process.execPath, script, "--status"], { env });
    expect(status.exitCode).toBe(0);
    expect(status.stdout.toString().split(/\r?\n/).filter(line => line.startsWith("linked"))).toHaveLength(links.length + 1);
    const repeated = Bun.spawnSync([process.execPath, script, "--execute", "--backup", "--force"], { env });
    expect(repeated.exitCode).toBe(0);
    expect(repeated.stdout.toString()).not.toContain("backup:");
  });

  it("preflights a collision before creating doctrine or replacing unrelated skills", () => {
    const profile = mkdtempSync(path.join(tmpdir(), "codex-collision-"));
    const custom = path.join(profile, "skills", "build");
    mkdirSync(custom, { recursive: true });
    writeFileSync(path.join(custom, "SKILL.md"), "custom content");
    const result = Bun.spawnSync([process.execPath, path.resolve(import.meta.dir, "../sync-codex.ts"), "--execute", "--force"], { env: { ...process.env, CODEX_HOME: profile } });
    expect(result.exitCode).toBe(1);
    expect(existsSync(path.join(profile, "AGENTS.md"))).toBe(false);
    expect(readFileSync(path.join(custom, "SKILL.md"), "utf8")).toBe("custom content");
  });
});

describe("Windows install fallback", () => {
  it("maps install method by platform: symlink on POSIX, junction/copy on win32", () => {
    expect(linkMethodFor("file", "darwin")).toBe("symlink");
    expect(linkMethodFor("directory", "linux")).toBe("symlink");
    expect(linkMethodFor("directory", "win32")).toBe("junction");
    expect(linkMethodFor("file", "win32")).toBe("copy");
  });

  it("treats a content-equal doctrine copy as linked on win32, local elsewhere", () => {
    const dir = mkdtempSync(path.join(tmpdir(), "codex-copy-"));
    const link = {
      source: path.join(dir, "CLAUDE.md"),
      dest: path.join(dir, "AGENTS.md"),
      type: "file" as const,
    };
    writeFileSync(link.source, "doctrine body\n");
    writeFileSync(link.dest, "doctrine body\n");
    expect(linkStatus(link, "win32")).toBe("linked");
    expect(linkStatus(link, "darwin")).toBe("local");
  });

  it("flags a stale copy as local on win32 (needs re-sync, not silence)", () => {
    const dir = mkdtempSync(path.join(tmpdir(), "codex-stale-"));
    const link = {
      source: path.join(dir, "CLAUDE.md"),
      dest: path.join(dir, "AGENTS.md"),
      type: "file" as const,
    };
    writeFileSync(link.source, "doctrine v2\n");
    writeFileSync(link.dest, "doctrine v1\n");
    expect(linkStatus(link, "win32")).toBe("local");
  });
});

describe("generated AGENTS.md (doctrine + system prompt)", () => {
  function makeLink() {
    const dir = mkdtempSync(path.join(tmpdir(), "codex-gen-"));
    const link = {
      source: path.join(dir, "CLAUDE.md"),
      dest: path.join(dir, "AGENTS.md"),
      type: "file" as const,
      concatSources: [path.join(dir, "poneglyph-sp.md")],
    };
    writeFileSync(link.source, "doctrine body\n");
    writeFileSync(link.concatSources[0], "system prompt body\n");
    return link;
  }

  it("concatenates all sources with a provenance header", () => {
    const link = makeLink();
    const content = generatedContent(link)!;
    expect(content).toStartWith("<!-- generated by sync-codex");
    expect(content).toContain("doctrine body");
    expect(content).toContain("system prompt body");
    expect(content.indexOf("doctrine body")).toBeLessThan(content.indexOf("system prompt body"));
  });

  it("content-equal generated file is linked; edited sources make it stale", () => {
    const link = makeLink();
    writeFileSync(link.dest, generatedContent(link)!);
    expect(linkStatus(link, "darwin")).toBe("linked");
    writeFileSync(link.concatSources[0], "system prompt body v2\n");
    expect(linkStatus(link, "darwin")).toBe("stale");
  });

  it("a pre-generated symlink install is a conflict; a hand-made file is local", () => {
    const link = makeLink();
    symlinkSync(link.source, link.dest);
    expect(linkStatus(link, "darwin")).toBe("conflict");
    const link2 = makeLink();
    writeFileSync(link2.dest, "hand-made content\n");
    expect(linkStatus(link2, "darwin")).toBe("local");
  });

  it("preserves an account link to matching shared generated doctrine", () => {
    const link = makeLink();
    const shared = path.join(path.dirname(link.dest), "shared-AGENTS.md");
    writeFileSync(shared, generatedContent(link)!);
    symlinkSync(shared, link.dest);
    expect(linkStatus(link)).toBe("linked");
    expect(lstatSync(link.dest).isSymbolicLink()).toBe(true);
    expect(readlinkSync(link.dest)).toBe(shared);
    writeFileSync(shared, "outdated shared doctrine\n");
    expect(linkStatus(link)).toBe("conflict");
  });
});
